[TOC]
# 异常
## 本章任务
- [ ] 掌握如何处理异常
- [ ] 掌握Java的异常是怎么抛出的
- [ ] 掌握自定义异常
- [ ] 掌握常见异常的处理方法

## 提要
异常其实我们并不陌生。在文件那一章节时就有提到过异常。那时我们只是将异常添加到方法上，但将任何异常都放到方法上，这样的做法并不符合开发规范。因此，从本章节开始我们必须学会如何正确处理异常以及如何解决异常。

## 异常的种类
在Java中异常分为运行时异常和编译异常。

运行时异常`RuntimeException`，和非运行时异常。在Java中有两个类负责定义异常——`RuntimeException`和`Exception`。其中`Exception`是非运行时异常。

运行时异常一般不要求处理，当程序异常时自动停止程序并打印错误日志。

非运行时异常是必须要处理的异常，如果不处理程序无法编译也就无法运行。在文件章节中看到的`IOException`这种就属于非运行时异常。

## 异常的处理

处理异常有两种方法：
1. 捕获-处理
2. 直接抛出

首先来说第一种处理方法——捕获-处理。

我们可以使用`try`关键字包裹一段代码，当这段代码中产生异常时会找到对应的`catch`语句执行。举例：

```java
File f = new File("demo.txt");
try {
    FileInputStream inputStream = new FileInputStream(f);
} catch (FileNotFoundException e) {
    throw new RuntimeException(e);
}
```
在这段代码中，当找不到文件`demo.txt`时会抛出`FileNotFoundException`异常，假设现在没有`demo.txt`文件，程序执行时，当程序执行到`File f=new File("demo.txt");`后，由于找不到文件，此时抛出了`FileNotFoundException`异常。由于我们捕获了`IOException`，此时执行了`throw new RuntimeException();`这条语句，而这个语句的作用就是抛出一个异常。此时我们程序因为异常结束了。

其中`throw new Exception();`就是对异常的处理，只不过这种方式简单粗暴，直接抛出。`throw`单词有抛出的意思，因此我们常说抛出变量。抛出变量并不是一个十分完美的处理方式。如果我们想让程序发生异常也还能运行就需要对异常进行比较好的处理而不是直接抛出。

如果我们不想让程序因为异常而结束可以看一下下面的两段代码：
```java
//代码1
File f = new File("demo.txt");
try {
    FileInputStream inputStream = new FileInputStream(f);
} catch (FileNotFoundException e) {
    throw new RuntimeException(e);
}
System.out.println("end");
//代码2
File f = new File("demo.txt");
try {
    FileInputStream inputStream = new FileInputStream(f);
} catch (FileNotFoundException e) {
    System.out.println("报错啦");
}
System.out.println("end");

```
这里有两段代码，第一段代码是一种简单的处理方式，第二段代码我们让它输出一个内容。

**分别**运行两段代码会发现第一段代码后面的end没有输出，而第二段代码输出了。

出现这个现象的原因是使用`throw`就会将异常向上抛出，而由于我们在主函数中抛出的异常，其上一级是调用主函数的东西，这个东西没有解决异常就会一直向上抛直到抛到虚拟机，虚拟机在拿到异常后就直接停止程序了。而第二段代码就相当于我们把这个异常解决了。解决的话就不再向上抛异常了。

第一种方法讲完，我们开始讲第二种方法，第二种方法是直接抛出和第一种方法的抛出有本质区别。方法一的抛出算是一种对异常的处理，因为是在捕获（`try`）后执行的，尽管最终的结果和没处理一样。而我们即将要将的第二种方法是不捕获，直接交给上一级处理。在开发中有时候也会使用这种情况。我们还是以刚才的例子为例，只不过这次我们不放在主函数中而是放在一个方法里。

```java
public class A{
    public static void mA() throws FileNotFoundException{
        File f = new File("demo.txt");
        FileInputStream inputStream = new FileInputStream(f);
    }
}
//Main.java中
public class Main{
    public static void main(String[] args){
        try{
            A.mA();
        }catch(FileNotFoundException e){
            System.out.println("捕捉到了异常，已处理");
        }
    }
}
```
我们可以看到在类A中的一个静态方法的定义中有一个`throws`关键字，这个关键字就是将异常抛出给上一级。其后面可以继续写很多个异常类。

我们以上面的代码为例讲讲发生了什么：

首先定义一个静态方法（只是为了方便调用而已，任何方法都可以抛出异常）。同时我们让该方法抛出mA，接下来我们在主函数中调用这个方法并进行捕获，执行后，由于文件不存在，mA方法抛出了`FileNotFoundException`异常。而mA方法抛出的异常在主函数中被捕获并解决所以程序没有影响。

如果我叛逆一些不捕获异常会发生什么？你会看到在mA方法下面有一条小红线：

![图 1](https://s2.loli.net/2023/09/10/WxHjUthecnEqCDQ.png)  

此时你的程序是无法编译成功的，**因为通过`throw`抛出的异常必须被捕获并处理**。
## 异常处理机制
从刚才的描述中应该也已经清楚异常是怎么抛出的。**首先先抛给调用者，然后再由调用者抛给主函数，最后由主函数抛出给虚拟机，当到虚拟机这个层级时程序就结束了。**

这里讲解一些什么是调用者，**调用A方法的那个方法B就是方法A的调用者**。我们看上一节中的代码：

```java
public class A{
    public static void mA() throws FileNotFoundException{
        File f = new File("demo.txt");
        FileInputStream inputStream = new FileInputStream(f);
    }
}
//Main.java中
public class Main{
    public static void main(String[] args){
        try{
            A.mA();
        }catch(FileNotFoundException e){
            System.out.println("捕捉到了异常，已处理");
        }
    }
}
```
这里的main就是方法mA的调用者。异常先抛给main方法，然后由main方法进行捕获。

那么是否意味着所有的异常都会被捕获呢？其实并不会，因为还有运行时异常，这种异常默认是不会被捕获的，除非特意指定一个`catch`进行强制捕获。

这里需要再强调一下，**如果异常通过`throws`关键字抛出，无论是不是运行时异常都必须处理。**

## 常见异常的处理
在编程中会经常遇到一些异常。那么怎样避免他们呢？这里提供一些小妙招：

|异常|产生原因|避免方法|
|:-|:-|:-|
|FileNotFoundException|文件不存在|在对应目录下创建一个文件|
|ArithmeticException|当提示“/ by zero”时表示除以0导致的出错|让除数不为0|
|ArrayIndexOutOfBoundsException|数组越界|让下标不要超过数组规定的长度|